### ISSUE TITLE
关于后台权限问题疑问

### ISSUE THREAD

**Issue by panda-men** [lizhenjian/leeAdmin#1]
你好，我看到后台默认又2个最高权限账户
一个admin，一个test
![image](https://user-images.githubusercontent.com/16631289/102952315-d37ae180-4509-11eb-881b-c1691e43ecfb.png)
test登录或新建一个超级管理员权限账户，
登录默认到checkAuth中间件是没有权限的：
![image](https://user-images.githubusercontent.com/16631289/102952604-6ca9f800-450a-11eb-8730-f4fc29081433.png)
会302跳转又会回到这里会死循环。

**Comment by lizhenjian** [comment]
![微信截图_20201225154807](https://user-images.githubusercontent.com/8486305/103126261-b2142400-46c8-11eb-9598-f2c1857dbb30.png)
这里有两个接口权限没有添加，因为admin是uid是1全部权限 test需要走理由验证。加上菜单权限 再将管理组勾选权限即可解决
